# Copyright © 2020-2019 Kontain Inc. All rights reserved.
#
# Kontain Inc CONFIDENTIAL
#
#  This file includes unpublished proprietary source code of Kontain Inc. The
#  copyright notice above does not evidence any actual or intended publication of
#  such source code. Disclosure of this source code or any related proprietary
#  information is strictly prohibited without the express written permission of
#  Kontain Inc.

obj-m += kkm.o
kkm-objs += kkm_fpu.o kkm_guest_entry.o kkm_guest_exit.o kkm_intr.o kkm_kontext.o kkm_mm.o kkm_platform_pv.o kkm_intr_table.o kkm_main.o kkm_mmu.o kkm_trace.o kkm_idt_cache.o kkm_kontainer.o kkm_misc.o kkm_platform_native.o
